<a href="https://colab.research.google.com/github/Yash-Wasalwar-07/TensorFlow-BootCamp/blob/main/Exercises/Tensorflow_Bootcamp_Ex0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`

In [2]:
import tensorflow as tf

In [3]:
# Scalar 
sc = tf.constant(4)
sc

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [4]:
sc.ndim

0

In [5]:
# Vector
vec = tf.constant([3,5,4,2,7])
vec

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 5, 4, 2, 7], dtype=int32)>

In [6]:
vec.ndim

1

In [7]:
# Matrix
mat = tf.constant([[10, 7],
                   [3,5]])
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5]], dtype=int32)>

In [8]:
mat.ndim, tf.size(mat), mat.shape

(2, <tf.Tensor: shape=(), dtype=int32, numpy=4>, TensorShape([2, 2]))

In [9]:
# Tensor -> Matrix of higher dimension
tens = tf.constant([[[10, 4, 3],
                     [4, 5, 6],
                     [2,1,7]],
                    
                    [[3, 5, 6],
                     [6, 7, 3],
                     [5, 3, 2]]])

tens

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[10,  4,  3],
        [ 4,  5,  6],
        [ 2,  1,  7]],

       [[ 3,  5,  6],
        [ 6,  7,  3],
        [ 5,  3,  2]]], dtype=int32)>

In [10]:
tens.ndim, tf.size(tens), tens.shape

(3, <tf.Tensor: shape=(), dtype=int32, numpy=18>, TensorShape([2, 3, 3]))

### 2. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [11]:
tf.random.set_seed(42)
rand_tens1 = tf.random.uniform(shape = [5, 300], seed = 42)
rand_tens1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.4163028 , 0.26858163, 0.47968316, ..., 0.9737669 , 0.9777365 ,
        0.21718514],
       [0.9787899 , 0.9768691 , 0.6782458 , ..., 0.8427533 , 0.8693787 ,
        0.6705674 ],
       [0.6826352 , 0.06621385, 0.58875644, ..., 0.7543584 , 0.38940334,
        0.7927996 ],
       [0.11849666, 0.60407066, 0.34777546, ..., 0.605     , 0.9107114 ,
        0.50104   ],
       [0.72606504, 0.7984501 , 0.9777988 , ..., 0.5601653 , 0.27684855,
        0.19102657]], dtype=float32)>

In [12]:
tf.random.set_seed(10)
rand_tens2 = tf.random.uniform(shape = [5, 300], seed = 10)
rand_tens2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.9574727 , 0.8584739 , 0.6193379 , ..., 0.05912542, 0.23000324,
        0.72254515],
       [0.6883857 , 0.7131387 , 0.15633631, ..., 0.3637315 , 0.4057479 ,
        0.5122801 ],
       [0.43793237, 0.4579332 , 0.8335929 , ..., 0.26972902, 0.69106436,
        0.10589242],
       [0.85208786, 0.8237473 , 0.22757328, ..., 0.44130492, 0.3482585 ,
        0.61636376],
       [0.24868822, 0.4261855 , 0.70794606, ..., 0.7709192 , 0.78888535,
        0.8316411 ]], dtype=float32)>

### 3. Multiply the two tensors you created in 2 using matrix multiplication.

In [13]:
tf.matmul(rand_tens1, tf.transpose(rand_tens2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.60192 , 79.6492  , 74.676056, 73.07554 , 73.21609 ],
       [75.903046, 75.29826 , 74.92006 , 68.098145, 75.397514],
       [73.67529 , 74.624466, 71.23102 , 71.03531 , 71.781525],
       [70.070694, 70.59462 , 69.29918 , 69.39799 , 67.6945  ],
       [80.589714, 78.4732  , 75.750015, 76.616844, 77.2422  ]],
      dtype=float32)>

### 4. Multiply the two tensors you created in 2 using dot product.

In [14]:
tf.tensordot(rand_tens1, tf.transpose(rand_tens2), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.60192 , 79.6492  , 74.676056, 73.07554 , 73.21609 ],
       [75.903046, 75.29826 , 74.92006 , 68.098145, 75.397514],
       [73.67529 , 74.624466, 71.23102 , 71.03531 , 71.781525],
       [70.070694, 70.59462 , 69.29918 , 69.39799 , 67.6945  ],
       [80.589714, 78.4732  , 75.750015, 76.616844, 77.2422  ]],
      dtype=float32)>

###5. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [15]:
tens_shape_3 = tf.random.uniform(shape = (224, 224, 3))
tens_shape_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.644151  , 0.8082472 , 0.8976548 ],
        [0.6368902 , 0.6270969 , 0.9936013 ],
        [0.02359486, 0.03668392, 0.5860578 ],
        ...,
        [0.4021759 , 0.87617314, 0.8240191 ],
        [0.5633031 , 0.2641574 , 0.59228563],
        [0.10286665, 0.53559935, 0.79840636]],

       [[0.6234499 , 0.56968355, 0.4731779 ],
        [0.4444275 , 0.20357692, 0.3325795 ],
        [0.6534798 , 0.37811399, 0.11533725],
        ...,
        [0.5544293 , 0.20996773, 0.13778448],
        [0.2790662 , 0.652912  , 0.7396562 ],
        [0.30591393, 0.7044697 , 0.74819875]],

       [[0.2532823 , 0.42836893, 0.43761683],
        [0.00777805, 0.6628947 , 0.01661897],
        [0.885396  , 0.5400171 , 0.06657803],
        ...,
        [0.79703116, 0.8331604 , 0.05939698],
        [0.6077355 , 0.30967402, 0.55589724],
        [0.4235295 , 0.61563694, 0.53281474]],

       ...,

       [[0.39041972, 0.29344285, 0.6998919 ],
        [0.46

### 6. Find the min and max values of the tensor you created in 5 along the first axis.


In [19]:
tf.reduce_max(tens_shape_3, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.99766874, 0.9974519 , 0.983027  ],
       [0.99258995, 0.9902681 , 0.9936013 ],
       [0.9918393 , 0.9934882 , 0.9859911 ],
       [0.9973062 , 0.9968287 , 0.9889674 ],
       [0.9985895 , 0.9951135 , 0.9947667 ],
       [0.9993118 , 0.9967475 , 0.9965998 ],
       [0.9996263 , 0.99856246, 0.9991648 ],
       [0.9951941 , 0.9983995 , 0.9990591 ],
       [0.9902729 , 0.99269176, 0.9927913 ],
       [0.9951664 , 0.9942634 , 0.9949511 ],
       [0.9940051 , 0.9950663 , 0.99887395],
       [0.9945004 , 0.99762404, 0.9997524 ],
       [0.9991329 , 0.9973091 , 0.9981177 ],
       [0.99334097, 0.9978061 , 0.9956708 ],
       [0.9963156 , 0.9996493 , 0.99544775],
       [0.9777496 , 0.98852265, 0.99376404],
       [0.9928211 , 0.9986869 , 0.995553  ],
       [0.9991796 , 0.99790263, 0.9961171 ],
       [0.9974432 , 0.98659873, 0.998842  ],
       [0.99506235, 0.9979907 , 0.9902464 ],
       [0.9991344 , 0.991189  , 0.9937097 ],
     

In [20]:
tf.reduce_max(tens_shape_3, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.9928062 , 0.9980675 , 0.9997524 ],
       [0.99941635, 0.9986869 , 0.9975852 ],
       [0.999969  , 0.9951135 , 0.99957883],
       [0.9976381 , 0.9958509 , 0.9968945 ],
       [0.9960369 , 0.99857557, 0.9951161 ],
       [0.9982908 , 0.99668825, 0.9846548 ],
       [0.9979577 , 0.99090266, 0.99904203],
       [0.99539936, 0.99870193, 0.9967017 ],
       [0.9932836 , 0.9933238 , 0.99578464],
       [0.9950526 , 0.9972105 , 0.9935088 ],
       [0.99473953, 0.9964031 , 0.9993398 ],
       [0.99438155, 0.99956083, 0.99312365],
       [0.99817896, 0.9990612 , 0.9934466 ],
       [0.9991087 , 0.99473596, 0.9965998 ],
       [0.99581194, 0.9995518 , 0.9887223 ],
       [0.9997989 , 0.99862754, 0.9993725 ],
       [0.9959086 , 0.9978061 , 0.9956708 ],
       [0.99786997, 0.98202646, 0.99671054],
       [0.9996594 , 0.9973211 , 0.9991169 ],
       [0.9993285 , 0.98977375, 0.99609804],
       [0.99781644, 0.99534833, 0.9952098 ],
     

In [21]:
tf.reduce_max(tens_shape_3, axis=2)

<tf.Tensor: shape=(224, 224), dtype=float32, numpy=
array([[0.8976548 , 0.9936013 , 0.5860578 , ..., 0.87617314, 0.59228563,
        0.79840636],
       [0.6234499 , 0.4444275 , 0.6534798 , ..., 0.5544293 , 0.7396562 ,
        0.74819875],
       [0.43761683, 0.6628947 , 0.885396  , ..., 0.8331604 , 0.6077355 ,
        0.61563694],
       ...,
       [0.6998919 , 0.822955  , 0.4960394 , ..., 0.9184462 , 0.9147731 ,
        0.9886668 ],
       [0.59955263, 0.7743714 , 0.6105881 , ..., 0.33000195, 0.5676875 ,
        0.4900844 ],
       [0.961483  , 0.68251693, 0.43224764, ..., 0.5250783 , 0.7027217 ,
        0.48501194]], dtype=float32)>

### 7. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [22]:
# New tensor
A = tf.random.uniform(shape = (1,224,224,3))
A

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.55478156, 0.42658198, 0.14140713],
         [0.703694  , 0.3726666 , 0.6976985 ],
         [0.23352468, 0.5646274 , 0.19849169],
         ...,
         [0.4680016 , 0.59981656, 0.16319764],
         [0.7872987 , 0.2642492 , 0.7624059 ],
         [0.6794454 , 0.131392  , 0.53645   ]],

        [[0.31601143, 0.05525446, 0.59130263],
         [0.6940526 , 0.8855659 , 0.01693177],
         [0.27555823, 0.86230123, 0.881135  ],
         ...,
         [0.5886234 , 0.6456871 , 0.9929285 ],
         [0.34501696, 0.352152  , 0.08070803],
         [0.5540197 , 0.08175528, 0.42444324]],

        [[0.0421083 , 0.3033743 , 0.77776253],
         [0.22907591, 0.23768401, 0.7568567 ],
         [0.4828955 , 0.9072578 , 0.9079046 ],
         ...,
         [0.1432209 , 0.56171536, 0.86918926],
         [0.6946225 , 0.35701978, 0.79232156],
         [0.7022995 , 0.21254289, 0.57867324]],

        ...,

        [[0.63443923, 0.48625624, 

In [23]:
squeeze_A = tf.squeeze(A)
squeeze_A

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.55478156, 0.42658198, 0.14140713],
        [0.703694  , 0.3726666 , 0.6976985 ],
        [0.23352468, 0.5646274 , 0.19849169],
        ...,
        [0.4680016 , 0.59981656, 0.16319764],
        [0.7872987 , 0.2642492 , 0.7624059 ],
        [0.6794454 , 0.131392  , 0.53645   ]],

       [[0.31601143, 0.05525446, 0.59130263],
        [0.6940526 , 0.8855659 , 0.01693177],
        [0.27555823, 0.86230123, 0.881135  ],
        ...,
        [0.5886234 , 0.6456871 , 0.9929285 ],
        [0.34501696, 0.352152  , 0.08070803],
        [0.5540197 , 0.08175528, 0.42444324]],

       [[0.0421083 , 0.3033743 , 0.77776253],
        [0.22907591, 0.23768401, 0.7568567 ],
        [0.4828955 , 0.9072578 , 0.9079046 ],
        ...,
        [0.1432209 , 0.56171536, 0.86918926],
        [0.6946225 , 0.35701978, 0.79232156],
        [0.7022995 , 0.21254289, 0.57867324]],

       ...,

       [[0.63443923, 0.48625624, 0.67542386],
        [0.13

### 8. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [33]:
# Single dimension tensor
tf.random.set_seed(23)
single_tensor = tf.constant([4,5,3,2,1,6,7,8,9,10])
single_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 4,  5,  3,  2,  1,  6,  7,  8,  9, 10], dtype=int32)>

In [34]:
tf.argmax(single_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

### 9. One-hot encode the tensor you created in 8

In [35]:
tf.one_hot(tf.cast(single_tensor, dtype = tf.int64), depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>